---
title: "Career Transition Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r}
library(tidyverse)
library(vroom)
library(here)
#functions-----------------------
make_plot <- function(noc, wage, job_openings, tbbl){
  temp <- tbbl%>%
    rename(Category=category)%>%
    group_by(Category)%>% #renaming
    mutate(Subcategory=fct_reorder(subcategory, `Attribute Deficit`))
  plt <- ggplot(temp, aes(`Attribute Deficit`, Subcategory, fill=Category))+
    geom_col()+
    labs(x="Need for improvement",
         y="",
         fill="")+
    coord_cartesian(xlim = c(0, 5))+ 
    scale_fill_brewer(palette = "Dark2")+
    scale_y_discrete(labels = NULL)+
    theme_minimal()
  plt <- plotly::ggplotly(plt)%>% 
    plotly::config(displayModeBar = F)%>%
    plotly::layout(font= list(size=9),
      title = list(text = paste0(noc,
                                    '<br>',
                                    '<sup>',
                                    'Average Wage: ',
                                    scales::dollar(wage),
                                    '         Job Openings: ',
                                    scales::comma(job_openings),
                                    '</sup>')))
  plotly::hide_legend(plt)
}
#load the data, do the PCA
jow <- vroom(here("processed_data","jow.csv"))
tbbl <- vroom(here("processed_data","scaled_characteristics_noc.csv"))%>%
  column_to_rownames(var="noc")
pca <- prcomp(tbbl)
first_pca <- pca[["x"]][,1:10]%>% #keep only the first 10 principal components.
    as.data.frame()
```

Inputs{.sidebar data-width=300}
-------------------------------------

* When you choose an occupation from the list below, this app finds the 6 closest occupations.
* Closeness is based on 165 attributes from 5 categories: 
    - Work activities 
    - Skills 
    - Knowledge 
    - Education/Experience/Training
    - Abilities
* The plots show the attributes most in need of improvement in order to switch occupations.
* The average wage rate and job openings for each occupation are also provided.



```{r}
selectInput(
  "noc",
  "Choose an occupation:",
  rownames(tbbl),
  selected = "41401: Economists and economic policy researchers and analysts",
  multiple = FALSE
)
```

```{r}
q <- first_pca[rownames(first_pca)=="41401: Economists and economic policy researchers and analysts",] #the location of the chosen NOC in 10D space.
temp <- dbscan::kNN(first_pca, k = 7, sort=TRUE,  query = q) #7 nearest neighbors to query (own NOC included)
nn <-  rownames(first_pca)[as.vector(temp[["id"]])] #the names of the closest occupations
chosen_noc <- tbbl[rownames(tbbl)=="41401: Economists and economic policy researchers and analysts",] #the skill profile of the chosen NOC (35D)

seven_chosen <- chosen_noc[rep(1, 7), ] #replicate the skill profile of the chosen NOC
temp <- tbbl[rownames(tbbl) %in% nn, ] #the nearest neighbour NOCs to the chosen NOC
closest <-   temp[nn, ] #orders the dataframe correctly

difference <- (closest-seven_chosen)%>% #the difference in skills
  mutate(across(everything(), \(x) round(x, 2)))%>%
  rownames_to_column(var="noc")%>%
  pivot_longer(cols=-noc, names_to = "all_category", values_to = "Attribute Deficit")%>%
  mutate(temp=all_category)%>%
  separate(temp, into = c("category","subcategory"), sep=": ")%>%
  filter(noc!="41401: Economists and economic policy researchers and analysts")%>%
  group_by(noc, category)%>%
  slice_max(order_by = `Attribute Deficit`, n = 5)%>%
  filter(`Attribute Deficit`>0)%>%
  group_by(noc)%>%
  nest()

difference <- difference%>%
  inner_join(jow)%>%
  mutate(plot=pmap(list(noc, wage, job_openings, data), make_plot))
```


 
Row
-------------------------------------
    
### 
    
```{r}
difference[["plot"]][[1]]
```
    
### 

```{r}
difference[["plot"]][[2]]
```


### 
    
```{r}
difference[["plot"]][[3]]
```
 
Row
------------------------------------- 
 
### 

```{r}
difference[["plot"]][[4]]
```

    
### 
    
```{r}
difference[["plot"]][[5]]
```
    
### 

```{r}
difference[["plot"]][[6]]
```




